apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend 
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template: 
    spec: 
      containers:
      - name: front
        image: gcr.io/bank-of-anthos/frontend:v0.5.1
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: LOG_LEVEL
          value: "info"
